# Generated by Django 4.1.4 on 2022-12-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarrerasModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cantidad_ano', models.IntegerField()),
                ('cantidad_asignaturas', models.IntegerField()),
            ],
        ),
    ]
